export const ADD_CHAT = 'ADD_CHAT';
export const GET_ALL_CHATS_FAILURE = 'GET_ALL_CHATS_FAILURE';
export const GET_ALL_CHATS_SUCCESS = 'GET_ALL_CHATS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
